# Generated by Django 5.1.4 on 2025-03-16 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_no', models.PositiveIntegerField(default=1)),
                ('unit_title', models.CharField(max_length=255)),
                ('co_no', models.PositiveIntegerField(default=1)),
                ('co_title', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='Users.subject')),
            ],
            options={
                'db_table': 'Question Sets Table',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('mark', models.PositiveIntegerField(default=0)),
                ('levels', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Questions.questionset')),
            ],
            options={
                'db_table': 'Questions Table',
            },
        ),
    ]
