# Generated by Django 5.1.4 on 2025-03-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='levels',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='title',
        ),
    ]
